title: "Guilherme Medeiros"
description: "London-based iOS engineer"

url: "https://guibrasil.github.io"   # no trailing slash
baseurl: "/guibrasilmed"              # note the leading slash

remote_theme: poole/hyde@v2.1.0
plugins:
  - jekyll-remote-theme
